config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  resources :cursos do
    resources :aulas, only: [:show, :update]
  end
  devise_for :users
  root "static_pages#home"
  get "/about" => "static_pages#about"

  get 'quiz/question', to: 'quiz#question'
  post 'quiz/answer', to: 'quiz#answer'
  get 'quiz/result', to: 'quiz#result'

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, except: :home
  def home
    set_meta_tags title: 'Rookie Coder Network',
                  description: 'Descubra como iniciar ou avançar na sua jornada como desenvolvedor com nossos cursos práticos e acessíveis. 
                  Oferecemos conteúdos atualizados em Ruby, JavaScript, Python e outras tecnologias essenciais, capacitando iniciantes 
                  e entusiastas da programação a conquistarem seus objetivos na área de tecnologia.',
                  keywords: 'Rookie Coder Network,Programação, Codigos, Cursos TI, Tecnologia, Aprendizado, Certificados, Cursos online,cursos de programação para iniciantes'
    @active_nav_item = 'home'
  end
  def courses
    
    @active_nav_item = 'courses'
  end
  def about
    set_meta_tags title: '',
                  description: '',
                  keywords: ''
    @active_nav_item = 'about'
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<main class="py-12 px-4">
    <div class="container mx-auto">
        <section class="bg-gray-800 rounded-lg p-6 mb-8">
            <h2 class="text-2xl font-bold mb-4">A Rookie Coder Network</h2>
            <p class="text-gray-300">
                Nosso site é uma plataforma dedicada a desenvolvedores, onde você pode compartilhar conhecimento, aprender novas técnicas e interagir com a comunidade. Aqui, você encontrará artigos sobre Front-end, Back-end, Full-stack, Desenvolvimento Mobile, Desenvolvimento Web e Ciência de Dados. Nosso objetivo é criar um espaço colaborativo e enriquecedor para todos os entusiastas da tecnologia.
            </p>
        </section>

        <section class="bg-gray-800 rounded-lg p-6">
            <h2 class="text-2xl font-bold mb-4">Equipe de Desenvolvedores</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <div class="bg-gray-700 rounded-lg p-4">
                    <h3 class="text-xl font-semibold mb-2">James Peter</h3>
                    <p class="text-gray-300 mb-2">Olá, sou um entusiasta da programação e estudante dedicado na UFRN, tenho 18 anos, trilhando meu caminho para me tornar um desenvolvedor full-stack. Apaixonado por desafios e aprendizado contínuo. (dica: Na duvida pergunte pro Rafa).</p>
                    <a href="https://www.linkedin.com/in/james-barbosa-289842235/" class="text-blue-400 hover:text-blue-300 mr-4" target="_blank">LinkedIn</a>
                    <a href="https://github.com/Jmspter" class="text-gray-400 hover:text-gray-300" target="_blank">GitHub</a>
                </div>
                <div class="bg-gray-700 rounded-lg p-4">
                    <h3 class="text-xl font-semibold mb-2">Rafael Claudeniro</h3>
                    <p class="text-gray-300 mb-2">Salve! Sou o Rafa, e é um prazer tê-lo(a) por aqui! Tenho 22 anos e desde pequeno tive um grande interesse em explorar o mundo Tech e graças a muita curiosidade venho me mantendo motivado todos os dias a aprender e ensinar cada vez mais Atualmente, sou estudante de Engenharia de Software com 2 anos de experiência em desenvolvimento web full-stack e me especializando em Segurança da Informação.</p>
                    <a href="https://www.linkedin.com/in/claudeniro-rafael/" class="text-blue-400 hover:text-blue-300 mr-4" target="_blank">LinkedIn</a>
                    <a href="https://github.com/Rafazg" class="text-gray-400 hover:text-gray-300" target="_blank">GitHub</a>
                </div>
                <div class="bg-gray-700 rounded-lg p-4">
                    <h3 class="text-xl font-semibold mb-2">Ana Luiza</h3>
                    <p class="text-gray-300 mb-2">Oiie, sou a Ana e tenho 18 anos Como uma amante de tecnologia posso dizer, a criança que buscava saber como eram feitos os jogos de navegador finalmete descobriu! E que época boa... Bom, estudo atualmente sobre todas as áreas da tec, confesso que fico encantanda pela cyber security! Meu objetivo é me tornar uma grande analista de dados.</p>
                    <a href="https://www.linkedin.com/in/ana-luiza-rodrigues-machado-625129274/" class="text-blue-400 hover:text-blue-300 mr-4" target="_blank">LinkedIn</a>
                    <a href="https://github.com/Lolita0000" class="text-gray-400 hover:text-gray-300" target="_blank">GitHub</a>
                </div>
                <div class="bg-gray-700 rounded-lg p-4">
                    <h3 class="text-xl font-semibold mb-2">Isabela Castro</h3>
                    <p class="text-gray-300 mb-2">Eu sou a Isabela, tenho 19 anos, comecei nessa área através de um curso técnico em Desenvolvimento de Sistemas que finalizei em 2022. Atualmente, faço faculdade de Bacharelado em Ciência da Computação na UFSCar (Universidade Federal de São Carlos). Sou uma garota apaixonada por códigos e café!</p>
                    <a href="https://www.linkedin.com/in/isabela-castro-43299125a/" class="text-blue-400 hover:text-blue-300 mr-4" target="_blank">LinkedIn</a>
                    <a href="https://github.com/IsabeladpCastro" class="text-gray-400 hover:text-gray-300" target="_blank">GitHub</a>
                </div>
                <div class="bg-gray-700 rounded-lg p-4">
                    <h3 class="text-xl font-semibold mb-2">Mateus Souza</h3>
                    <p class="text-gray-300 mb-2">Olá, mundo! Eu sou o Mateus, tenho 24 anos, comecei nessa área com 23 anos e gosto muito do que venho fazendo, desde jovem já gostava muito de tecnologia e quero sempre estar aprendendo mais sobre. Atualmente faço graduação em tecnólogo em Análise e Desenvolvimento de Sistemas e busco ser um desenvolvedor FullStack.</p>
                    <a href="https://www.linkedin.com/in/mateus-souza-025b48232/" class="text-blue-400 hover:text-blue-300 mr-4" target="_blank">LinkedIn</a>
                    <a href="https://github.com/MattSouza14" class="text-gray-400 hover:text-gray-300" target="_blank">GitHub</a>
                </div>
                <div class="bg-gray-700 rounded-lg p-4">
                    <h3 class="text-xl font-semibold mb-2">Saymon Medeiros</h3>
                    <p class="text-gray-300 mb-2">Fala pessoal! Me chamo Saymon e tenho 23 anos, sou apaixonado por tecnologia e atualmente estou focado nos estudos de HTML e CSS. Meu objetivo é me tornar um desenvolvedor fullstack, abrangendo tanto o desenvolvimento de front-end quanto o de back-end. Estou entusiasmado com minha jornada de aprendizado e ansioso para construir uma carreira sólida no desenvolvimento web.</p>
                    <a href="https://www.linkedin.com/in/saymon-medeiros-2b5025232/" class="text-blue-400 hover:text-blue-300 mr-4" target="_blank">LinkedIn</a>
                    <a href="https://github.com/saymonmedeiros/" class="text-gray-400 hover:text-gray-300" target="_blank">GitHub</a>
                </div>
            </div>
        </section>
    </div>
</main>

app/views/static_pages/home.html.erb
<section class="md:flex space-around items-center justify-center">
  <div class="md:w-1/2 mx-5">
    <h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight md:text-5xl lg:text-6xl">JUNTOS, VAMOS TRANSFORMAR CÓDIGOS EM CONQUISTAS!</h1>
    <p class="mb-6 text-lg font-normal text-gray-400 lg:text-xl">Empoderando novos desenvolvedores a trilharem seu caminho no mundo da programação!</p>
    <a href="/articles" class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center bg-lime-700 rounded-lg hover:bg-lime-800 focus:ring-4 focus:ring-lime-300 dark:focus:ring-lime-900">
        Bora começar
        <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
      </svg>
    </a>      
  </div>
  <div class="mt-10">
    <%= image_tag("image01.svg") %>
  </div>
</section>
<section class="md:flex flex-row-reverse">
      <div class="md:w-1/2 mx-5 flex flex-col justify-center items-center">
      <h1 class="mb-4 text-3xl font-extrabold leading-none tracking-tight md:text-5xl lg:text-3xl">ENCONTRE-SE NA ÁREA DE TI</h1>
      <p class="mb-6 text-lg font-normal text-gray-400 lg:text-xl">Faça o nosso teste vocacional, descubra sua area e dê um play em sua carreira.</p>

      <%= link_to quiz_question_path do %>
      <button class="relative p-8 bg-lime-500 text-white rounded-full focus:outline-none hover:bg-lime-600 transition duration-300 group">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-12 h-12 fill-current group-hover:scale-110 transform transition-transform duration-300 ease-out" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <polygon points="5 3 19 12 5 21 5 3"></polygon>
        </svg>
      </button> 
      <% end %>
      </div>
      <div>
      <%= image_tag("image02.svg") %>
     </div>
</section>