config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  resources :cursos do
    resources :aulas, only: [:show, :update]
  end
  devise_for :users
  root "static_pages#home"
  get "/about" => "static_pages#about"

  get 'quiz/question', to: 'quiz#question'
  post 'quiz/answer', to: 'quiz#answer'
  get 'quiz/result', to: 'quiz#result'

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/layouts/_footer.html.erb
<footer class="rounded-lg shadow bg-gray-900 m-4">
<div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
    <div class="sm:flex sm:items-center sm:justify-between">
        <a href="/" class="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
            <%= image_tag("rokie.png", class:"h-8") %>
        </a>
        <ul class="flex flex-wrap items-center mb-6 text-sm font-medium text-gray-400 sm:mb-0">
            <li>
                <a href="/about" class="hover:underline me-4 md:me-6">About</a>
            </li>
            <li>
                <a href="#" class="hover:underline me-4 md:me-6">Privacy Policy</a>
            </li>
            <li>
                <a href="#" class="hover:underline me-4 md:me-6">Licensing</a>
            </li>
            <li>
                <a href="#" class="hover:underline">Contact</a>
            </li>
        </ul>
    </div>
    <hr class="my-6 sm:mx-auto border-gray-700 lg:my-8" />
    <span class="block text-sm text-gray-400 sm:text-center">© 2024 <a href="/" class="hover:underline">Rookie Coder Network</a>. All Rights Reserved.</span>
</div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="bg-gray-900 border-gray-700 mb-4">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
            <%= image_tag("rokie.png", class:"h-8") %>
        </a>
        <button data-collapse-toggle="navbar-hamburger" type="button" class="inline-flex items-center justify-center p-2 w-10 h-10 text-sm text-gray-400 rounded-lg hover:bg-gray-700 focus:outline-none focus:ring-gray-600 focus:ring-gray-200" aria-controls="navbar-hamburger" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
        </button>
        <div class="hidden w-full" id="navbar-hamburger">
        <ul class="flex flex-col font-medium mt-4 rounded-lg bg-gray-800 border-gray-700">
            <li>
                <%= link_to "Home", root_path, class: nav_link_class('home') %>
            </li>
            <li>
                <%= link_to "Cursos", cursos_path, class: nav_link_class('courses') %>
            </li>
            <li>
                <%= link_to "Network", articles_path, class: nav_link_class('network') %>
            </li>
            <li>
                <%= link_to "Sobre nós", about_path, class: nav_link_class('about') %>
            </li>
            <% if user_signed_in? %>
            <li><%= link_to 'Sair', destroy_user_session_path, data: { "turbo-method": :delete }, class:"block py-2 px-3 text-gray-400 rounded hover:bg-gray-700 hover:text-red-500" %></li>
            <% else %>
            <li>
                <%= link_to "Login", new_user_session_path, class:"block py-2 px-3 text-gray-400 rounded hover:bg-gray-700 hover:text-white" %>
            </li>
            <li>
                <%= link_to "Register", new_user_registration_path, class:"block py-2 px-3 text-gray-400 rounded hover:bg-gray-700 hover:text-white" %>
            </li>
            <% end %>
        </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: "Rookie Coder Network" %>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body class="bg-gray-950 text-white">
    <main class="bg-gray-950 text-white">
      <%= render 'layouts/nav' %>
      <% if alert.present? %>
        <div class="div-alert " id="notice" id="alert">
          <span><%= alert %></span>
          <button class="px-1 py-1 right-0 mt-1 mr-1 text-red-500 hover:text-red-700 text-2xl leading-none" onclick="document.getElementById('alert').style.display = 'none';">
          </button>
        </div>
      <% end %>
      <% if notice.present? %>
        <div class="div-notice" id="notice">
          <span class="pr-2"><%= notice %></span>
          <button class="px-1 py-1 right-0 mt-1 mr-1 text-green-500 hover:text-green-700 text-2xl leading-none" onclick="document.getElementById('notice').style.display = 'none';">
          </button>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </main>
    <script>
        function hideAlert(name){
          const alert = document.getElementById(name)
          if(alert){
            setTimeout(()=>{
              alert.style.display ='none'
            }, 2000)
          }
        }
        hideAlert('alert')
        hideAlert('notice')
    </script>
  </body>
</html>